export type ProjectStatus = 'active' | 'paused' | 'completed' | 'archived'
export type Priority = 'high' | 'medium' | 'low'
export type TodoConfirmationStatus = 'confirmed' | 'rejected'
export type ProjectAccessRole = 'owner' | 'member'
export type JournalVisibility = 'private' | 'public'

export type JournalEntry = {
  id: number
  createdAt: string
  content: string
  authorUserId?: number
  speakerName: string
  visibility: JournalVisibility
}

export type Todo = {
  id: number
  projectId: number
  createdAt: string
  createdByUserId?: number
  creatorName?: string
  assigneeUserId?: number
  assigneeName?: string
  assignedByUserId?: number
  assignedByName?: string
  title: string
  detail: string
  dueDate: string
  priority: Priority
  done: boolean
  confirmationStatus: TodoConfirmationStatus
  linkedToDeliveryEvent: boolean
  moduleId?: number
  moduleName?: string
  notes: TodoNote[]
}

export type ProjectModule = {
  id: number
  projectId: number
  name: string
  createdAt: string
}

export type TodoNote = {
  id: number
  todoId: number
  authorUserId?: number
  authorName: string
  content: string
  createdAt: string
  updatedAt: string
  sourceOperationId?: number
}

export type ProjectMembership = {
  id: number
  projectId: number
  invitedUsername: string
  invitedUserId?: number
  role: ProjectAccessRole
  status: 'pending' | 'active' | 'declined'
  memberName: string
  createdAt: string
}

export type NotificationState = {
  readAt?: string
  dismissedAt?: string
}

export type ProjectInviteNotification = NotificationState & {
  id: number
  projectId: number
  projectName: string
  invitedByName: string
  createdAt: string
}

export type TodoNotification = NotificationState & {
  id: number
  projectId: number
  projectName: string
  moduleName?: string
  title: string
  dueDate: string
  priority: Priority
  done?: boolean
  assignedAt?: string
  assignedByName?: string
  noteId?: number
  noteAuthorName?: string
  notePreview?: string
  createdAt?: string
  type?: 'assigned' | 'due_tomorrow' | 'note_mention'
}

export type PackageEventNotification = NotificationState & {
  assignedAt?: string
  assignedByName?: string
  eventStatus: ProjectPackageEventStatus
  eventType: ProjectPackageEventType
  id: number
  projectId: number
  projectName: string
  title: string
}

export type NotificationCenterData = {
  assignedPackageEvents: PackageEventNotification[]
  assignedTodos: TodoNotification[]
  dueTomorrowTodos: TodoNotification[]
  noteMentions: TodoNotification[]
  invites: ProjectInviteNotification[]
}

export type InboxItem = {
  id: number
  source: 'manual' | 'feishu'
  content: string
  createdAt: string
  suggestedProjectId?: number
  processed: boolean
}

export type Summary = {
  id: number
  projectId?: number
  type: 'weekly' | 'monthly'
  title: string
  period: string
  content: string
  createdAt: string
}

export type ProjectPackageEventType = 'init' | 'upgrade'
export type ProjectPackageEventStatus = 'draft' | 'delivering' | 'delivered'
export type ProjectPackageOperationStatus = 'failed' | 'pending' | 'success'
export type ProjectPackageOperationKind = 'document' | 'event'
export type PackageMarketChannel = 'release' | 'ci'

export type ProjectPackageItem = {
  id: number
  sourcePackageId: string
  sourcePackageName: string
  packageName: string
  channel: string
  channelLabel: string
  arch: string
  version: string
  objectKey: string
  objectLastModified?: string
  sizeBytes?: number
  createdAt: string
}

export type ProjectPackageOperation = {
  id: number
  kind: ProjectPackageOperationKind
  status: ProjectPackageOperationStatus
  title: string
  label: string
  content: string
  relatedTodoIds: number[]
  relatedTodoNotes: Record<number, string>
  completed: boolean
  autoGenerated: boolean
  createdAt: string
  updatedAt: string
}

export type ProjectPackageGroup = {
  id: number
  packageName: string
  items: ProjectPackageItem[]
  operations: ProjectPackageOperation[]
}

export type ProjectPackageEvent = {
  assignedAt?: string
  assignedByName?: string
  assignedByUserId?: number
  assigneeName?: string
  assigneeUserId?: number
  id: number
  type: ProjectPackageEventType
  status: ProjectPackageEventStatus
  title: string
  createdAt: string
  deliveryDate: string
  updatedAt: string
  operations: ProjectPackageOperation[]
  groups: ProjectPackageGroup[]
}

export type ProjectPackageTimeline = {
  projectId: number
  events: ProjectPackageEvent[]
}

export type PackageMarketRule = {
  id: string
  name: string
  category: 'apps' | 'middleware' | 'dependency'
  mode: 'release' | 'flat' | 'mixed' | 'pro-middleware'
  releaseRoots: string[]
  flatFileRoots: string[]
  dependencyRoots?: string[]
  dependencyFilePatterns?: string[]
  parent?: string
  fileNameFormats: string[]
  ciFileNameFormats: string[]
}

export type PackageMarketVersion = {
  version?: string
  hash?: string
  label: string
  lastModified?: string
}

export type PackageMarketLink = {
  name: string
  version: string
  objectKey: string
  size?: number
  lastModified?: string
  downloadUrl: string
  expiresAt?: string
  expiresInSeconds?: number
}

export type PackageMarketDetail = {
  title: string
  type: string
  meta: Array<{ label: string; value: string }>
  links: PackageMarketLink[]
  releaseVersions?: PackageMarketVersion[]
  ciVersions?: PackageMarketVersion[]
  selectedHash?: string
}

export type Project = {
  id: number
  accessRole: ProjectAccessRole
  name: string
  description: string
  ownerName: string
  ownerUserId: number
  status: ProjectStatus
  feishuChatEnabled?: boolean
  feishuChatId?: string
  createdAt: string
  updatedAt: string
  tags: string[]
  journals: JournalEntry[]
  risks: string[]
  riskJournalEntryIds: number[]
  modules: ProjectModule[]
}
